-- g5pro: 쇼핑몰 테이블 접두사 yc5_ → g5_shop_ (26개)
-- 되돌리기: 좌우를 바꿔 같은 문장을 실행
RENAME TABLE
  `yc5_banner` TO `g5_shop_banner`,
  `yc5_cart` TO `g5_shop_cart`,
  `yc5_category` TO `g5_shop_category`,
  `yc5_coupon` TO `g5_shop_coupon`,
  `yc5_coupon_log` TO `g5_shop_coupon_log`,
  `yc5_coupon_zone` TO `g5_shop_coupon_zone`,
  `yc5_default` TO `g5_shop_default`,
  `yc5_event` TO `g5_shop_event`,
  `yc5_event_item` TO `g5_shop_event_item`,
  `yc5_inicis_log` TO `g5_shop_inicis_log`,
  `yc5_inicis_pay` TO `g5_shop_inicis_pay`,
  `yc5_inicis_pay_event` TO `g5_shop_inicis_pay_event`,
  `yc5_item` TO `g5_shop_item`,
  `yc5_item_option` TO `g5_shop_item_option`,
  `yc5_item_qa` TO `g5_shop_item_qa`,
  `yc5_item_relation` TO `g5_shop_item_relation`,
  `yc5_item_stocksms` TO `g5_shop_item_stocksms`,
  `yc5_item_use` TO `g5_shop_item_use`,
  `yc5_order` TO `g5_shop_order`,
  `yc5_order_address` TO `g5_shop_order_address`,
  `yc5_order_data` TO `g5_shop_order_data`,
  `yc5_order_delete` TO `g5_shop_order_delete`,
  `yc5_order_post_log` TO `g5_shop_order_post_log`,
  `yc5_personalpay` TO `g5_shop_personalpay`,
  `yc5_sendcost` TO `g5_shop_sendcost`,
  `yc5_wish` TO `g5_shop_wish`;
