-- g5pro 3단계: 제로데이트 추방
-- date/datetime NOT NULL 컬럼 66 개를 NULL DEFAULT NULL 로 바꾸고
-- 남아있는 0000-00-00 값을 NULL 로 정리한다.
-- strict 모드에서 DEFAULT 없는 NOT NULL 은 INSERT 누락 시 에러가 나므로 NULL 허용으로 간다.

-- [1] 컬럼 정의
ALTER TABLE `g5_autosave` MODIFY COLUMN `as_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_board_file` MODIFY COLUMN `bf_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_board_good` MODIFY COLUMN `bg_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_board_new` MODIFY COLUMN `bn_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_cert_history` MODIFY COLUMN `cr_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_config` MODIFY COLUMN `cf_optimize_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_group_member` MODIFY COLUMN `gm_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_login` MODIFY COLUMN `lo_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_mail` MODIFY COLUMN `ma_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_nick_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_today_login` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_email_certify` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_mailling_date` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_sms_date` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_open_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_marketing_date` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member` MODIFY COLUMN `mb_thirdparty_date` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member_cert_history` MODIFY COLUMN `ch_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member_social_profiles` MODIFY COLUMN `mp_register_day` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_member_social_profiles` MODIFY COLUMN `mp_latest_day` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_memo` MODIFY COLUMN `me_send_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_memo` MODIFY COLUMN `me_read_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_new_win` MODIFY COLUMN `nw_begin_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_new_win` MODIFY COLUMN `nw_end_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_point` MODIFY COLUMN `po_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_point` MODIFY COLUMN `po_expire_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_poll` MODIFY COLUMN `po_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_poll_etc` MODIFY COLUMN `pc_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_popular` MODIFY COLUMN `pp_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_qa_content` MODIFY COLUMN `qa_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_scrap` MODIFY COLUMN `ms_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_banner` MODIFY COLUMN `bn_begin_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_banner` MODIFY COLUMN `bn_end_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_banner` MODIFY COLUMN `bn_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_cart` MODIFY COLUMN `ct_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_cart` MODIFY COLUMN `ct_select_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_coupon` MODIFY COLUMN `cp_start` date NULL DEFAULT NULL;
ALTER TABLE `g5_shop_coupon` MODIFY COLUMN `cp_end` date NULL DEFAULT NULL;
ALTER TABLE `g5_shop_coupon` MODIFY COLUMN `cp_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_coupon_log` MODIFY COLUMN `cl_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_coupon_zone` MODIFY COLUMN `cz_start` date NULL DEFAULT NULL;
ALTER TABLE `g5_shop_coupon_zone` MODIFY COLUMN `cz_end` date NULL DEFAULT NULL;
ALTER TABLE `g5_shop_coupon_zone` MODIFY COLUMN `cz_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_item` MODIFY COLUMN `it_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_item` MODIFY COLUMN `it_update_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_item_qa` MODIFY COLUMN `iq_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_item_stocksms` MODIFY COLUMN `ss_send_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_item_stocksms` MODIFY COLUMN `ss_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_item_use` MODIFY COLUMN `is_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_order` MODIFY COLUMN `od_receipt_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_order` MODIFY COLUMN `od_hope_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_shop_order` MODIFY COLUMN `od_invoice_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_order` MODIFY COLUMN `od_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_order_data` MODIFY COLUMN `dt_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_order_delete` MODIFY COLUMN `de_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_order_post_log` MODIFY COLUMN `ol_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_personalpay` MODIFY COLUMN `pp_receipt_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_personalpay` MODIFY COLUMN `pp_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_shop_wish` MODIFY COLUMN `wi_time` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_visit` MODIFY COLUMN `vi_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_visit_sum` MODIFY COLUMN `vs_date` date NULL DEFAULT NULL;
ALTER TABLE `g5_write_free` MODIFY COLUMN `wr_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_write_gallery` MODIFY COLUMN `wr_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_write_notice` MODIFY COLUMN `wr_datetime` datetime NULL DEFAULT NULL;
ALTER TABLE `g5_write_qa` MODIFY COLUMN `wr_datetime` datetime NULL DEFAULT NULL;

-- [2] 값 정리
UPDATE `g5_autosave` SET `as_datetime` = NULL WHERE `as_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_board_file` SET `bf_datetime` = NULL WHERE `bf_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_board_good` SET `bg_datetime` = NULL WHERE `bg_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_board_new` SET `bn_datetime` = NULL WHERE `bn_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_cert_history` SET `cr_date` = NULL WHERE `cr_date` = "0000-00-00";
UPDATE `g5_config` SET `cf_optimize_date` = NULL WHERE `cf_optimize_date` = "0000-00-00";
UPDATE `g5_group_member` SET `gm_datetime` = NULL WHERE `gm_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_login` SET `lo_datetime` = NULL WHERE `lo_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_mail` SET `ma_time` = NULL WHERE `ma_time` = "0000-00-00 00:00:00";
UPDATE `g5_member` SET `mb_nick_date` = NULL WHERE `mb_nick_date` = "0000-00-00";
UPDATE `g5_member` SET `mb_today_login` = NULL WHERE `mb_today_login` = "0000-00-00 00:00:00";
UPDATE `g5_member` SET `mb_datetime` = NULL WHERE `mb_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_member` SET `mb_email_certify` = NULL WHERE `mb_email_certify` = "0000-00-00 00:00:00";
UPDATE `g5_member` SET `mb_mailling_date` = NULL WHERE `mb_mailling_date` = "0000-00-00 00:00:00";
UPDATE `g5_member` SET `mb_sms_date` = NULL WHERE `mb_sms_date` = "0000-00-00 00:00:00";
UPDATE `g5_member` SET `mb_open_date` = NULL WHERE `mb_open_date` = "0000-00-00";
UPDATE `g5_member` SET `mb_marketing_date` = NULL WHERE `mb_marketing_date` = "0000-00-00 00:00:00";
UPDATE `g5_member` SET `mb_thirdparty_date` = NULL WHERE `mb_thirdparty_date` = "0000-00-00 00:00:00";
UPDATE `g5_member_cert_history` SET `ch_datetime` = NULL WHERE `ch_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_member_social_profiles` SET `mp_register_day` = NULL WHERE `mp_register_day` = "0000-00-00 00:00:00";
UPDATE `g5_member_social_profiles` SET `mp_latest_day` = NULL WHERE `mp_latest_day` = "0000-00-00 00:00:00";
UPDATE `g5_memo` SET `me_send_datetime` = NULL WHERE `me_send_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_memo` SET `me_read_datetime` = NULL WHERE `me_read_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_new_win` SET `nw_begin_time` = NULL WHERE `nw_begin_time` = "0000-00-00 00:00:00";
UPDATE `g5_new_win` SET `nw_end_time` = NULL WHERE `nw_end_time` = "0000-00-00 00:00:00";
UPDATE `g5_point` SET `po_datetime` = NULL WHERE `po_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_point` SET `po_expire_date` = NULL WHERE `po_expire_date` = "0000-00-00";
UPDATE `g5_poll` SET `po_date` = NULL WHERE `po_date` = "0000-00-00";
UPDATE `g5_poll_etc` SET `pc_datetime` = NULL WHERE `pc_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_popular` SET `pp_date` = NULL WHERE `pp_date` = "0000-00-00";
UPDATE `g5_qa_content` SET `qa_datetime` = NULL WHERE `qa_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_scrap` SET `ms_datetime` = NULL WHERE `ms_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_shop_banner` SET `bn_begin_time` = NULL WHERE `bn_begin_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_banner` SET `bn_end_time` = NULL WHERE `bn_end_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_banner` SET `bn_time` = NULL WHERE `bn_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_cart` SET `ct_time` = NULL WHERE `ct_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_cart` SET `ct_select_time` = NULL WHERE `ct_select_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_coupon` SET `cp_start` = NULL WHERE `cp_start` = "0000-00-00";
UPDATE `g5_shop_coupon` SET `cp_end` = NULL WHERE `cp_end` = "0000-00-00";
UPDATE `g5_shop_coupon` SET `cp_datetime` = NULL WHERE `cp_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_shop_coupon_log` SET `cl_datetime` = NULL WHERE `cl_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_shop_coupon_zone` SET `cz_start` = NULL WHERE `cz_start` = "0000-00-00";
UPDATE `g5_shop_coupon_zone` SET `cz_end` = NULL WHERE `cz_end` = "0000-00-00";
UPDATE `g5_shop_coupon_zone` SET `cz_datetime` = NULL WHERE `cz_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_shop_item` SET `it_time` = NULL WHERE `it_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_item` SET `it_update_time` = NULL WHERE `it_update_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_item_qa` SET `iq_time` = NULL WHERE `iq_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_item_stocksms` SET `ss_send_time` = NULL WHERE `ss_send_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_item_stocksms` SET `ss_datetime` = NULL WHERE `ss_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_shop_item_use` SET `is_time` = NULL WHERE `is_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_order` SET `od_receipt_time` = NULL WHERE `od_receipt_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_order` SET `od_hope_date` = NULL WHERE `od_hope_date` = "0000-00-00";
UPDATE `g5_shop_order` SET `od_invoice_time` = NULL WHERE `od_invoice_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_order` SET `od_time` = NULL WHERE `od_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_order_data` SET `dt_time` = NULL WHERE `dt_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_order_delete` SET `de_datetime` = NULL WHERE `de_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_shop_order_post_log` SET `ol_datetime` = NULL WHERE `ol_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_shop_personalpay` SET `pp_receipt_time` = NULL WHERE `pp_receipt_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_personalpay` SET `pp_time` = NULL WHERE `pp_time` = "0000-00-00 00:00:00";
UPDATE `g5_shop_wish` SET `wi_time` = NULL WHERE `wi_time` = "0000-00-00 00:00:00";
UPDATE `g5_visit` SET `vi_date` = NULL WHERE `vi_date` = "0000-00-00";
UPDATE `g5_visit_sum` SET `vs_date` = NULL WHERE `vs_date` = "0000-00-00";
UPDATE `g5_write_free` SET `wr_datetime` = NULL WHERE `wr_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_write_gallery` SET `wr_datetime` = NULL WHERE `wr_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_write_notice` SET `wr_datetime` = NULL WHERE `wr_datetime` = "0000-00-00 00:00:00";
UPDATE `g5_write_qa` SET `wr_datetime` = NULL WHERE `wr_datetime` = "0000-00-00 00:00:00";
